
package com.sise.suppliertype;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://supplierType.sise.com/")
public class Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.sise.supplier.Exception faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Exception(String message, com.sise.supplier.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Exception(String message, com.sise.supplier.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.sise.supplier.Exception
     */
    public com.sise.supplier.Exception getFaultInfo() {
        return faultInfo;
    }

}
