
package com.sise.suppliertype;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SupplierTypeServiceImpl", targetNamespace = "http://supplierType.sise.com/")
@XmlSeeAlso({
    com.sise.supplier.ObjectFactory.class,
    com.sise.suppliertype.ObjectFactory.class
})
public interface SupplierTypeServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.sise.suppliertype.SupplierType
     * @throws Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getType", targetNamespace = "http://supplierType.sise.com/", className = "com.sise.suppliertype.GetType")
    @ResponseWrapper(localName = "getTypeResponse", targetNamespace = "http://supplierType.sise.com/", className = "com.sise.suppliertype.GetTypeResponse")
    @Action(input = "http://supplierType.sise.com/SupplierTypeServiceImpl/getTypeRequest", output = "http://supplierType.sise.com/SupplierTypeServiceImpl/getTypeResponse", fault = {
        @FaultAction(className = Exception.class, value = "http://supplierType.sise.com/SupplierTypeServiceImpl/getType/Fault/Exception")
    })
    public SupplierType getType(
        @WebParam(name = "arg0", targetNamespace = "")
        SupplierType arg0)
        throws Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setSupplierTypeDao", targetNamespace = "http://supplierType.sise.com/", className = "com.sise.suppliertype.SetSupplierTypeDao")
    @ResponseWrapper(localName = "setSupplierTypeDaoResponse", targetNamespace = "http://supplierType.sise.com/", className = "com.sise.suppliertype.SetSupplierTypeDaoResponse")
    @Action(input = "http://supplierType.sise.com/SupplierTypeServiceImpl/setSupplierTypeDaoRequest", output = "http://supplierType.sise.com/SupplierTypeServiceImpl/setSupplierTypeDaoResponse")
    public void setSupplierTypeDao(
        @WebParam(name = "arg0", targetNamespace = "")
        SupplierTypeDaoImpl arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.sise.suppliertype.SupplierType>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTypeList", targetNamespace = "http://supplierType.sise.com/", className = "com.sise.suppliertype.GetTypeList")
    @ResponseWrapper(localName = "getTypeListResponse", targetNamespace = "http://supplierType.sise.com/", className = "com.sise.suppliertype.GetTypeListResponse")
    @Action(input = "http://supplierType.sise.com/SupplierTypeServiceImpl/getTypeListRequest", output = "http://supplierType.sise.com/SupplierTypeServiceImpl/getTypeListResponse")
    public List<SupplierType> getTypeList();

}
