
package com.sise.supplier;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SupplierServiceImpl", targetNamespace = "http://supplier.sise.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SupplierServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.sise.supplier.Supplier>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findSupplierAjax", targetNamespace = "http://supplier.sise.com/", className = "com.sise.supplier.FindSupplierAjax")
    @ResponseWrapper(localName = "findSupplierAjaxResponse", targetNamespace = "http://supplier.sise.com/", className = "com.sise.supplier.FindSupplierAjaxResponse")
    @Action(input = "http://supplier.sise.com/SupplierServiceImpl/findSupplierAjaxRequest", output = "http://supplier.sise.com/SupplierServiceImpl/findSupplierAjaxResponse")
    public List<Supplier> findSupplierAjax(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.sise.supplier.Supplier>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSupplierList", targetNamespace = "http://supplier.sise.com/", className = "com.sise.supplier.GetSupplierList")
    @ResponseWrapper(localName = "getSupplierListResponse", targetNamespace = "http://supplier.sise.com/", className = "com.sise.supplier.GetSupplierListResponse")
    @Action(input = "http://supplier.sise.com/SupplierServiceImpl/getSupplierListRequest", output = "http://supplier.sise.com/SupplierServiceImpl/getSupplierListResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://supplier.sise.com/SupplierServiceImpl/getSupplierList/Fault/Exception")
    })
    public List<Supplier> getSupplierList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setSupplierDao", targetNamespace = "http://supplier.sise.com/", className = "com.sise.supplier.SetSupplierDao")
    @ResponseWrapper(localName = "setSupplierDaoResponse", targetNamespace = "http://supplier.sise.com/", className = "com.sise.supplier.SetSupplierDaoResponse")
    @Action(input = "http://supplier.sise.com/SupplierServiceImpl/setSupplierDaoRequest", output = "http://supplier.sise.com/SupplierServiceImpl/setSupplierDaoResponse")
    public void setSupplierDao(
        @WebParam(name = "arg0", targetNamespace = "")
        SupplierDaoImpl arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sise.supplier.Supplier
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSupplier", targetNamespace = "http://supplier.sise.com/", className = "com.sise.supplier.GetSupplier")
    @ResponseWrapper(localName = "getSupplierResponse", targetNamespace = "http://supplier.sise.com/", className = "com.sise.supplier.GetSupplierResponse")
    @Action(input = "http://supplier.sise.com/SupplierServiceImpl/getSupplierRequest", output = "http://supplier.sise.com/SupplierServiceImpl/getSupplierResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://supplier.sise.com/SupplierServiceImpl/getSupplier/Fault/Exception")
    })
    public Supplier getSupplier(
        @WebParam(name = "arg0", targetNamespace = "")
        Supplier arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.sise.supplier.Supplier>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findSupplier", targetNamespace = "http://supplier.sise.com/", className = "com.sise.supplier.FindSupplier")
    @ResponseWrapper(localName = "findSupplierResponse", targetNamespace = "http://supplier.sise.com/", className = "com.sise.supplier.FindSupplierResponse")
    @Action(input = "http://supplier.sise.com/SupplierServiceImpl/findSupplierRequest", output = "http://supplier.sise.com/SupplierServiceImpl/findSupplierResponse")
    public List<Supplier> findSupplier(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
